<?php
/**
 * @file
 * Code for the DAB Primo Search feature.
 */

include_once 'dab_primo_search.features.inc';
/**
 * @file
 * Define ctools plugin for DAB search.
 */

/**
 * Implements hook_ctools_plugin_directory().
 */
function dab_primo_search_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/content_types';
  }
}
